#!/bin/bash
VHOST_FILE=/etc/apache2/extra/httpd-vhosts.conf
HOST_FILE=/etc/hosts



if [[ $UID != 0 ]]; then
	echo "This script requires root"
	echo "sudo $0 $*"
	exit 1
fi

echo "##################################################"
echo "##################################################"
echo "########  APACHE CONFIGURATION BUILDER  ##########"
echo "########        by Atticus White        ##########"
echo "##################################################"
echo "##################################################"


currentDir=${PWD}
currentDir="$currentDir/"





function createIndex {
	indexFile="$projectDirectory/index.html"
	touch $indexFile
	chown "$SUDO_USER" "$indexFile"
	chmod 775 "$indexFile"
	
	echo "<h2>It works!</h2>" >> "$indexFile"
	echo "<code>" >> "$indexFile"
	echo "Project Name: $projectName<br/>" >> "$indexFile"
	echo "Project Location: $projectDirectory<br/>" >> "$indexFile"
	echo "Project Domain: $projectDomain<br/>" >> "$indexFile"
	echo "<br/><br/><br/>" >> "$indexFile"
	echo "<small>Generated by Atticus White's Apache Configuration Builder" >> "$indexFile"
	echo "</code>" >> "$indexFile"
	
}






## PROJECT NAME
read -p "New Project Name: " projectName

## PROJECT DOMAIN NAME
read -p "New Domain Name: " projectDomain



## PROJECT DIRECTORY
projectDirectory=""

read -p "Is your project residing in $currentDir (Y/N): " projectInCwd

if [ "$projectInCwd" == "Y" ]; then
	read -p "What is the name of your project directory? " folderName
	
	projectDirectory="$currentDir$folderName"
else
	read -p "What is the full path of your project directory?" projectDirectory
fi

echo "Directory: $projectDirectory"

if [ ! -d "$projectDirectory" ]; then
	read -p "Directory does not exist, would you like to create it? (Y/N): " createDirectory
	
	if [ "$createDirectory" == "Y" ]; then
		echo "Creating Directory $projectDirectory"
		mkdir $projectDirectory
		chown "$SUDO_USER" "$projectDirectory"
		chmod 775 $projectDirectory
		createIndex
	fi
fi



## HOST FILE
echo "127.0.0.1	$projectDomain"  >> $HOST_FILE


echo "


## $projectName
#
<VirtualHost *:80>
        ServerAdmin     contact@atticuswhite.com
        DocumentRoot    \"$projectDirectory\"
        ServerName      $projectDomain
        ErrorLog        \"/private/var/log/apache2/$projectDomain-error_log\"
        CustomLog       \"/private/var/log/apache2/$projectDomain-access_log\" common

        <Directory \"$projectDirectory\">
                Options Indexes Includes FollowSymLinks MultiViews
                AllowOverride AuthConfig FileInfo
                Order allow,deny
                Allow from all
        </Directory>
</VirtualHost>" >> $VHOST_FILE


apachectl restart

open -a "Google Chrome" "http://$projectDomain"